@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.adex.demo.domain.models.CustomerRequestsQueue#get()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.adex.demo.domain.models.CustomerRequestsQueue",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_2989078 { 
   	label=adex
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1882568891 { 
   	label=demo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_258336939 { 
   	label=CustomerRequestsQueue
	labeljust=l
	fillcolor=white
	style=filled
   
   CustomerRequestsQueue273129844XXXget0[
	label="+ get()"
	style=filled
	fillcolor=white
	tooltip="CustomerRequestsQueue

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_418069620 { 
   	label=CustomerRequestsProcessor
	labeljust=l
	fillcolor=white
	style=filled
   
   CustomerRequestsProcessor1157377110XXXprocessCustomerRequest0[
	label="+ processCustomerRequest()"
	style=filled
	fillcolor=white
	tooltip="CustomerRequestsProcessor

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
CustomerRequestsProcessor1157377110XXXprocessCustomerRequest0 -> CustomerRequestsQueue273129844XXXget0;
    
}
@enduml