services:
  mysqldb:
    image: mysql:latest
    container_name: adex-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=adex_db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
