networks:
  demo-network:
    driver: bridge

services:
  adex-mysql:
    image: mysql:latest
    container_name: adex-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=adex_db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - demo-network
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
  adex-demo:
    image: safinrraf/sample_demo
    depends_on:
      adex-mysql:
        condition: service_healthy
    container_name: adex-demo
    ports:
      - "8080:8080"
    networks:
      - demo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MYSQL_HOST=adex-mysql
      - DB_USERNAME=root
      - DB_PASSWORD=123456789
