networks:
  demo-network:
    driver: bridge

services:
  adex-mysql:
    image: mysql:latest
    container_name: adex-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=ADEX_DB
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - demo-network
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
  adex-hazelcast:
    image: hazelcast/hazelcast:latest
    container_name: adex-hazelcast
    environment:
      - JAVA_OPTS=-Dhazelcast.diagnostics.directory=/opt/hazelcast/logs -Dhazelcast.diagnostics.metric.level=info -Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml -Xmx512m -Xms256m -Dhazelcast.diagnostics.enabled=true -Dhazelcast.security.recommendations
    volumes:
      - ./hazelcast/hazelcast.xml:/opt/hazelcast/config_ext/hazelcast.xml
      - ./hazelcast/logs:/opt/hazelcast/logs
    ports:
      - "5701:5701"
    networks:
      - demo-network
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5701/hazelcast/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  adex-demo:
    image: safinrraf/sample_demo
    depends_on:
      adex-mysql:
        condition: service_healthy
      adex-hazelcast:
        condition: service_healthy
    container_name: adex-demo
    ports:
      - "8080:8080"
    networks:
      - demo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MYSQL_HOST=adex-mysql
      - DB_USERNAME=root
      - DB_PASSWORD=123456789
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/adex-demo/internal/monitoring/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s